max_width = 80
comment_width = 80
wrap_comments = true
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_strings = true
hex_literal_case = "Upper"
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
tab_spaces = 4
use_field_init_shorthand = true
where_single_line = true
